name: Report an issue with blazingkraft.com website
description: Tell us if something is not working as expected
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that there isn't already an open issue describing the same problem.
  - type: dropdown
    id: package
    attributes:
      label: What Blazing Playground feature has an issue
      options:
        - 'OpenAPI Definition'
        - 'Schemas Definition'
        - 'OpenAPI Content'
        - 'Schemas Content'
        - 'Content Validation'
        - 'Content Diff'
        - 'Conversions'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: dropdown
    id: fix
    attributes:
      label: Do you have any idea on how to fix it?
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix